# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.24)

{

# ____________________________________________________________________
# FLAKE INPUTS
# ____________________________________________________________________
  
  inputs = {
    nixpkgs = {
      url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*";
    };
    flake-schemas = {
      url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";  
    };
    determinate = {
      url = "https://flakehub.com/f/DeterminateSystems/determinate/*";
    };
    fh = {
      url = "https://flakehub.com/f/DeterminateSystems/fh/*";
    };
    flake-utils = {
      url = "github:numtide/flake-utils";
    };
    chaotic = {
      url = "github:chaotic-cx/nyx/nyxpkgs-unstable";
    };
    jovian = {
      follows = "chaotic/jovian";
    };
    nixos-cosmic = {
      url = "github:lilyinstarlight/nixos-cosmic";
    };
    bcachefs-tools = {
      url = "github:koverstreet/bcachefs-tools";
    };
    nix-software-center = {
      url = "github:snowfallorg/nix-software-center";
    };
  }; 

# ____________________________________________________________________
# FLAKE OUTPUTS
# ____________________________________________________________________
  
  outputs = inputs@{ self, nixpkgs, flake-schemas, determinate, fh, flake-utils, chaotic, jovian, ... }:
    
    let
      
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    
    in {
      
      # Schemas tell Nix about the structure of your flake's outputs
      schemas = flake-schemas.schemas;

      
      # Development environments
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          packages = [
            pkgs.nixpkgs-fmt
          ];
        };
      });
     
  # __________________________________________________________________
  # NIXOS SYSTEM CONFIGURATIONS
  # __________________________________________________________________

      nixosConfigurations = {

      # ______________________________________________________________
      # NOTEBOOK-ACER
      # ______________________________________________________________
        
        NOTEBOOK-ACER = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          specialArgs = { inherit inputs; };
          
          modules = [
          # ----------------------------------------------------------
            {
              environment.systemPackages = [ 
                fh.packages.x86_64-linux.default
                inputs.nix-software-center.packages.${system}.nix-software-center
              ];
            }
          # ----------------------------------------------------------
            determinate.nixosModules.default
            chaotic.nixosModules.default
          # ----------------------------------------------------------
            ./configuration.nix
          # ----------------------------------------------------------
            ./hosts/NOTEBOOK-ACER/default.nix
          # ----------------------------------------------------------
            ./modules/default.nix
          # ----------------------------------------------------------
            ./modules/cosmic/default.nix
          # ----------------------------------------------------------
          ];
        };

      # ______________________________________________________________
      # DESKTOP-HP
      # ______________________________________________________________
        
        DESKTOP-HP = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          specialArgs = { inherit inputs; };
          
          modules = [
          # ----------------------------------------------------------
            {
              environment.systemPackages = [ 
                fh.packages.x86_64-linux.default 
              ];
            }
          # ----------------------------------------------------------
            determinate.nixosModules.default
            chaotic.nixosModules.default
            jovian.nixosModules.default
          # ----------------------------------------------------------
            ./configuration.nix
          # ----------------------------------------------------------
            ./hosts/DESKTOP-HP/default.nix
          # ----------------------------------------------------------
            ./modules/default.nix
          # ----------------------------------------------------------
            ./modules/jovian/default.nix
          # ----------------------------------------------------------
          ];
        };
      
      };
    };
}
